### PR TITLE
Beginning Backbone Implementation

### PR DESCRIPTION
**Pull request by mcverter**
Started Backbone Implementation.
There are still a few areas that can be optimized.

Changes:
buoy-alert.js ==>  replaced most of the jQuery with Backbone objects
buoy.js          ==> removed reference to "attachHandlers"
class-buoy-alert.php  ==> added javascript dependencies (underscore, jquery, backbone)

### CODE REVIEW

**Comment by mcverter** [comment]
See some errors

**Comment by mcverter** [comment]
Please test this and let me know if you require further changes.  The code is sound, as far as I can tell

**Comment by mcverter** [comment]
I have some errors still.  Sorry about this.  Will fix this up asap

**Comment by fabacab** [comment]
Thanks so much for your time on this, @mcverter. I'm merging this as a squashed commit because there are a lot of commits in this but they all represent one logical chunk of work.

**Pull request merged**
